---
title: My Blog
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    lang: en
    category: articles
email: gautambaliblog@gmail.com
description: 'Personal Thoughts and opinions of a commom man about general politics
  and "Punjabi Legacy"

'
baseurl: "/baliblogs"
url: https://baliblogs.github.io
markdown: kramdown
exclude:
- vendor
- Gemfile
- Gemfile.lock
permalink: "/:title.html"
jekyll-theme-simple-blog:
  date_format: "%b %-d, %Y"
theme: 
header_page_refs:
- coding
- projects
- about
plugins:
- jekyll-target-blank
target-blank:
  rel: nofollow
show_post_image_posts_list: false
header:
  image: "/assets/patterns/symphony.png"
author:
  name: Bali's Blog
  short_bio:
    en: Ideas and Opinions, Responsive
  picture: assets/img/profile-60.png
image: "/assets/img/profile-225.png"
t:
  en:
    latest-posts: Latest Posts
    read-more: Read More →
    show-more: Show More →
    loading: Loading...
    on-word: 'on'
    contact: Contact
    contact-page: contact.md
    read-time: min read
    comments: comments
    go-to-home-page: Go to the Home Page
    months:
      january: Jan
      february: Feb
      march: Mar
      april: Apr
      may: May
      june: Jun
      july: Jul
      august: Aug
      september: Sep
      october: Oct
      november: Nov
      december: Dec
  it:
    latest-posts: Ultimi Posts
    read-more: Leggi →
    show-more: Mostra →
    loading: Caricamento...
    on-word: su
    contact: Contatta
    contact-page: contatta.md
    read-time: min di lettura
    comments: commenti
    go-to-home-page: Vai alla Pagina Iniziale
    months:
      january: Gen
      february: Feb
      march: Mar
      april: Apr
      may: Mag
      june: Giu
      july: Lug
      august: Ago
      september: Set
      october: Ott
      november: Nov
      december: Dic
